<?xml version="1.0" encoding="utf-8"?><Database Name="UrlShortener" Class="UrlShortenerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=UrlShortener;Integrated Security=True" SettingsObjectName="UrlShortener.Data.Properties.Settings" SettingsPropertyName="UrlShortenerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.URLs" Member="URLs">
    <Type Name="URL">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UrlOrig" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UrlShort" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Views" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_URL" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="User_URL" Member="URLs" ThisKey="Id" OtherKey="UserId" Type="URL" />
    </Type>
  </Table>
</Database>